{"level":"info","timestamp":"2025-01-04T19:43:23.892+0300","msg":"app initialized successfully"}
{"level":"info","timestamp":"2025-01-04T20:19:31.097+0300","msg":"app initialized successfully"}
{"level":"info","timestamp":"2025-01-04T20:23:29.837+0300","msg":"registering user"}
{"level":"info","timestamp":"2025-01-04T20:28:38.015+0300","msg":"app initialized successfully"}
{"level":"info","timestamp":"2025-01-04T20:28:43.381+0300","msg":"registering user"}
{"level":"info","timestamp":"2025-01-04T20:30:07.863+0300","msg":"app initialized successfully"}
{"level":"info","timestamp":"2025-01-04T20:30:11.061+0300","msg":"registering user"}
{"level":"info","timestamp":"2025-01-04T20:30:40.584+0300","msg":"app initialized successfully"}
{"level":"info","timestamp":"2025-01-04T20:30:46.079+0300","msg":"registering user"}
{"level":"info","timestamp":"2025-01-04T20:31:28.263+0300","msg":"app initialized successfully"}
{"level":"info","timestamp":"2025-01-04T20:31:31.627+0300","msg":"registering user"}
{"level":"fatal","timestamp":"2025-01-04T20:38:35.762+0300","msg":"failed to create db client:","error":"failed to connect to db: failed to connect to `host=localhost user=note-user database=note`: failed SASL auth (FATAL: password authentication failed for user \"note-user\" (SQLSTATE 28P01))","errorVerbose":"failed to connect to db: failed to connect to `host=localhost user=note-user database=note`: failed SASL auth (FATAL: password authentication failed for user \"note-user\" (SQLSTATE 28P01))\ngithub.com/igortoigildin/goph-keeper/internal/client/db/pg.New\n\t/Users/igortoigildin/Desktop/Dev/goph-keeper/internal/client/db/pg/client.go:19\ngithub.com/igortoigildin/goph-keeper/internal/server/app.(*serviceProvider).DBClient\n\t/Users/igortoigildin/Desktop/Dev/goph-keeper/internal/server/app/service_provider.go:100\ngithub.com/igortoigildin/goph-keeper/internal/server/app.(*serviceProvider).UserRepository\n\t/Users/igortoigildin/Desktop/Dev/goph-keeper/internal/server/app/service_provider.go:120\ngithub.com/igortoigildin/goph-keeper/internal/server/app.(*serviceProvider).AuthService\n\t/Users/igortoigildin/Desktop/Dev/goph-keeper/internal/server/app/service_provider.go:85\ngithub.com/igortoigildin/goph-keeper/internal/server/app.(*serviceProvider).AuthImpl\n\t/Users/igortoigildin/Desktop/Dev/goph-keeper/internal/server/app/service_provider.go:92\ngithub.com/igortoigildin/goph-keeper/internal/server/app.(*App).initGRPCServer\n\t/Users/igortoigildin/Desktop/Dev/goph-keeper/internal/server/app/app.go:79\ngithub.com/igortoigildin/goph-keeper/internal/server/app.(*App).initDeps\n\t/Users/igortoigildin/Desktop/Dev/goph-keeper/internal/server/app/app.go:55\ngithub.com/igortoigildin/goph-keeper/internal/server/app.NewApp\n\t/Users/igortoigildin/Desktop/Dev/goph-keeper/internal/server/app/app.go:30\nmain.main\n\t/Users/igortoigildin/Desktop/Dev/goph-keeper/cmd/server/main.go:17\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:272\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_arm64.s:1223"}
{"level":"info","timestamp":"2025-01-04T20:46:55.590+0300","msg":"app initialized successfully"}
{"level":"info","timestamp":"2025-01-04T20:46:59.703+0300","msg":"registering user"}
{"level":"error","timestamp":"2025-01-04T20:46:59.775+0300","msg":"failed to save user","error":"error while creating user: ERROR: syntax error at or near \"user\" (SQLSTATE 42601)"}
{"level":"error","timestamp":"2025-01-04T20:46:59.775+0300","msg":"registration error","error":"auth.RegisterNewUser: error while creating user: ERROR: syntax error at or near \"user\" (SQLSTATE 42601)"}
{"level":"info","timestamp":"2025-01-04T20:50:18.075+0300","msg":"app initialized successfully"}
{"level":"info","timestamp":"2025-01-04T20:50:24.120+0300","msg":"registering user"}
{"level":"error","timestamp":"2025-01-04T20:50:24.195+0300","msg":"failed to save user","error":"error while creating user: ERROR: syntax error at or near \"user\" (SQLSTATE 42601)"}
{"level":"error","timestamp":"2025-01-04T20:50:24.195+0300","msg":"registration error","error":"auth.RegisterNewUser: error while creating user: ERROR: syntax error at or near \"user\" (SQLSTATE 42601)"}
{"level":"info","timestamp":"2025-01-04T20:51:17.172+0300","msg":"app initialized successfully"}
{"level":"info","timestamp":"2025-01-04T20:51:20.369+0300","msg":"registering user"}
{"level":"error","timestamp":"2025-01-04T20:51:20.441+0300","msg":"failed to save user","error":"error while creating user: ERROR: relation \"users\" does not exist (SQLSTATE 42P01)"}
{"level":"error","timestamp":"2025-01-04T20:51:20.442+0300","msg":"registration error","error":"auth.RegisterNewUser: error while creating user: ERROR: relation \"users\" does not exist (SQLSTATE 42P01)"}
{"level":"info","timestamp":"2025-01-04T20:53:41.291+0300","msg":"app initialized successfully"}
{"level":"info","timestamp":"2025-01-04T20:53:48.154+0300","msg":"registering user"}
{"level":"error","timestamp":"2025-01-04T20:53:48.225+0300","msg":"failed to save user","error":"error while creating user: ERROR: relation \"users\" does not exist (SQLSTATE 42P01)"}
{"level":"error","timestamp":"2025-01-04T20:53:48.225+0300","msg":"registration error","error":"auth.RegisterNewUser: error while creating user: ERROR: relation \"users\" does not exist (SQLSTATE 42P01)"}
{"level":"info","timestamp":"2025-01-04T21:01:32.145+0300","msg":"app initialized successfully"}
{"level":"info","timestamp":"2025-01-04T21:01:37.725+0300","msg":"registering user"}
{"level":"error","timestamp":"2025-01-04T21:01:37.796+0300","msg":"failed to save user","error":"error while creating user: ERROR: relation \"users\" does not exist (SQLSTATE 42P01)"}
{"level":"error","timestamp":"2025-01-04T21:01:37.796+0300","msg":"registration error","error":"auth.RegisterNewUser: error while creating user: ERROR: relation \"users\" does not exist (SQLSTATE 42P01)"}
{"level":"info","timestamp":"2025-01-04T21:02:03.057+0300","msg":"app initialized successfully"}
{"level":"info","timestamp":"2025-01-04T21:02:07.967+0300","msg":"registering user"}
{"level":"error","timestamp":"2025-01-04T21:02:08.040+0300","msg":"failed to save user","error":"error while creating user: ERROR: relation \"users\" does not exist (SQLSTATE 42P01)"}
{"level":"error","timestamp":"2025-01-04T21:02:08.040+0300","msg":"registration error","error":"auth.RegisterNewUser: error while creating user: ERROR: relation \"users\" does not exist (SQLSTATE 42P01)"}
{"level":"info","timestamp":"2025-01-04T21:03:14.534+0300","msg":"app initialized successfully"}
{"level":"info","timestamp":"2025-01-04T21:03:22.421+0300","msg":"registering user"}
{"level":"error","timestamp":"2025-01-04T21:03:22.493+0300","msg":"failed to save user","error":"error while creating user: ERROR: relation \"users\" does not exist (SQLSTATE 42P01)"}
{"level":"error","timestamp":"2025-01-04T21:03:22.493+0300","msg":"registration error","error":"auth.RegisterNewUser: error while creating user: ERROR: relation \"users\" does not exist (SQLSTATE 42P01)"}
{"level":"info","timestamp":"2025-01-04T21:11:18.464+0300","msg":"app initialized successfully"}
{"level":"info","timestamp":"2025-01-04T21:11:25.023+0300","msg":"registering user"}
{"level":"info","timestamp":"2025-01-04T21:11:25.099+0300","msg":"user registered"}
